<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1f09756af25e4dc1a357306db6befd4a
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Filebase\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Filebase\\' => 
        array (
            0 => __DIR__ . '/..' . '/filebase/filebase/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1f09756af25e4dc1a357306db6befd4a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1f09756af25e4dc1a357306db6befd4a::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
